model_list:
  - model_name: gpt-4o
    litellm_params:
      model: zhipu/glm-4.5-air
      api_key: ""  # Leave empty for user to fill in

general_settings:
  master_key: "9SMwnbAdv27hdXGp76QzK97k6Kxth5pWHNqPzuOeTWEX9laP"